spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:C:/BERTRAND/h2_db
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate.SQL: DEBUG
    org.h2: DEBUG
