spring:
  profiles:
    active: @spring.profiles.active@

logging:
  level:
    root: INFO
    com.bta: DEBUG
    org:
      springframework:
        web: ERROR
        amqp: DEBUG
      hibernate.SQL: INFO
      h2: INFO


axon:
  serializer:
    general: JACKSON
    events: JACKSON
    messages: JACKSON