spring:
  profiles:
    include:
      - rabbitmq
  datasource:
    url: jdbc:mysql://localhost:3306/bta
    username: bta
    password: bta
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway.baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  rabbitmq:
    host: localhost
    port: 5672

rabbitmq:
  queueName: bta.queue
  exchangeName: bta-exchange
  routingKey: bta.routingkey

axon:
  amqp:
    exchange: axondemo-plr-events-exchg
    transaction-mode: transactional
  eventhandling:
    processors:
      amqpEvents:
        source: rabbitMQSpringAMQPMessageSource
        mode: tracking
