spring:
  profiles:
    active: @spring.profiles.active@

logging:
  level:
    root: INFO
    com.bta: DEBUG
    org.springframework.web: ERROR
    org.hibernate.SQL: INFO
    org.h2: INFO

axon:
  serializer:
    general: JACKSON
    events: JACKSON
    messages: JACKSON