apiVersion: apps/v1
kind: Deployment
metadata:
  name: axon-demo
  labels:
    app: axon-demo
spec:
  selector:
    matchLabels:
      app: axon-demo
  template:
    metadata:
      labels:
        app: axon-demo
    spec:
      containers:
        - name: axon-demo
          image: docker.io/library/axon-demo:local
          ports:
            - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: axon-demo
  namespace: axon-demo
  labels:
    app: axon-demo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30297
  selector:
    app: axon-demo
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}

---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 0

---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql
subsets:
  -
    addresses:
      -
        ip: 192.168.0.20
    ports:
      - port: 3306
        name: mysql