version: '3.5'

services:
  mysql:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: bta
      MYSQL_USER: bta
      MYSQL_PASSWORD: bta
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
       - /home/bta/docker/docker-mysql/data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
  
  adminer:
    container_name: adminer_container
    image: adminer
    ports:
      - "8085:8080"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

